# Custom routes used by the Wurrd Client Interface plugin


## -- Server Information

# This route is use to request for server details without providing authentication
wurrd_client_simple_server_info:
    # Relative path from the Mibew web root is used here.
    path: /wurrd/clientinterface/serverinfo
    # Set some defaults for the request
    defaults:
        # This value is special. It tells the system what action should be
        # invoked for the response
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\ServerController::simpleInfoAction
    methods: [GET]

# This route is use to request for server details with authentication
wurrd_client_detail_server_info:
    path: /wurrd/clientinterface/serverinfo/{apiver}/{accesstoken}/{clientrevision}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\ServerController::detailInfoAction
        clientrevision: 0
    methods: [GET]


## -- Operator interactions

wurrd_client_operator_login:
    # The login request details are passed in as a JSON payload.
    path: /wurrd/clientinterface/operator/login
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\OperatorController::loginAction
    methods: [PUT]


wurrd_client_operator_refresh_access:
    path: /wurrd/clientinterface/operator/refreshaccess/{accesstoken}/{refreshtoken}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\OperatorController::refreshAccessAction
    methods: [PUT]

wurrd_client_operator_logout:
    path: /wurrd/clientinterface/operator/logout/{accesstoken}/{deviceuuid}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\OperatorController::logoutAction
    methods: [DELETE]

wurrd_client_operator_users_update:
    path: /wurrd/clientinterface/operator/users/updatethreads/{clientrevision}/{accesstoken}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\UsersController::updateThreadsAction
    methods: [GET]
    requirements:
        clientrevision: \d{1,10}

# Here we expect a threads query parameter which is a JSON array of threads with the following parameters per entry:
#   - threadid
#   - token
#   - lastid
wurrd_client_operator_messages_update:
    path: /wurrd/clientinterface/operator/threads/updatemessages/{accesstoken}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\ThreadController::updateMessagesAction
    methods: [GET]

wurrd_client_operator_start_chat:
    path: /wurrd/clientinterface/operator/threads/start/{threadid}/{token}/{accesstoken}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\ThreadController::startChatAction
    methods: [PUT]
    requirements:
        threadid: \d{1,10}

wurrd_client_operator_close_chat:
    path: /wurrd/clientinterface/operator/threads/close/{threadid}/{token}/{accesstoken}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\ThreadController::closeChatAction
    methods: [PUT]
    requirements:
        threadid: \d{1,10}

# This route is an interface for the client operator to post a batch of messages, possibly for multiple threads
# A JSON array of messages is expected in the body of the POST request with the following fields:
#   - threadid
#   - token
#   - messages[] 
wurrd_client_operator_post_messages:
    path: /wurrd/clientinterface/operator/threads/post/{accesstoken}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\ThreadController::postMessagesAction
    methods: [POST]


# This is temporal. Use the batch processing option instead
wurrd_client_operator_post_message:
    path: /wurrd/clientinterface/operator/threads/post/{threadid}/{token}/{accesstoken}
    defaults:
        _controller: Wurrd\Mibew\Plugin\ClientInterface\Controller\ThreadController::postAMessageAction
    methods: [POST]



